### ISSUE TITLE
Would love to see directions....

### ISSUE THREAD

**Issue by amarand** [jhansche/pybirdbuddy#10]
I know this is a relatively new project, but I'd love to see a readme or install file that steps you through things like:

Required version(s) of Python
Python modules required
Which .py file(s) to execute to pull data
Step-by-step execution

I'm getting syntax errors and it's a little too early for me to digging.

**Comment by fury88** [comment]
Same issue here. Just opened one as well. I'm running 3.8.10 and getting an error with ""await" allowed only within async function". I'm guessing the version of python is causing this. I haven't gone into 3.9 yet. If there are requirements of other libraries I haven't seen anything that tells us either. My main error is "BirdBuddy is not logged in. Call refresh() first"

**Comment by fury88** [comment]
See my other thread. The readme was updated to include the result = asyncio.run(bb.refresh()) call. Try that if you haven't been able to log in yet.

**Comment by jhansche** [comment]
For the record, this library exists solely to support the Home Assistant integration: https://github.com/jhansche/ha-birdbuddy/. If it helps you with other projects, that's great. But my intent is not to make a library simple enough or suitable for a beginner to drop in.

Most of these questions can be answered by looking at the sources - i.e., see `setup.py`, `requirements.txt`, and `README.md`. If you install the package from PyPI, then all the dependencies (there's only one) got installed along with it.

```"await" allowed only within async function```
This is almost certainly because you're trying to call an async coroutine function from a non-async context. That means the function you're calling it from is not marked as `async`, or you're trying to call it from a top-level script file (i.e., `python testing.py`). This is simply how coroutines work, and I don't think it's the responsibility of a library to explain that.

If you want something ready-made and easy to use, you're welcome to use the Home Assistant integration - either in HA directly, or as an example for how the library is used: https://github.com/jhansche/ha-birdbuddy/ You can also look at the tests (both here and in ha-birdbuddy).

**Comment by jhansche** [comment]
As for the required Python version, since this is intended to be used in the Home Assistant integration, it's only tested with Python 3.9 and 3.10 (which is now the minimum for running HA, so Python 3.9 will likely no longer be tested here, but the GitHub action workflow still lists it in the version matrix)
